server:
  port: 8080


owinfo:
  upload:
    enabled: true
    #FTP?FASTDFS?MINIO, 还是FTP好用
    type: FTP
    # 预览nginxUrl + remoteDir + "/" + fileRemoteName
    nginxUrl: http://192.168.20.20:80
  ftp:
    host: 192.168.20.20
    port: 21
    username: ftpuser
    password: ftpuser
    # 服务端需要关闭http token验证机制
  fastdfs:
    trackerServers: 192.168.20.20:22122
  minio:
    endpoint: http://192.168.20.20:9000
    username: minioadmin
    password: minioadmin

spring:
  servlet:
    multipart:
      max-file-size: 100M
      max-request-size: 100M
