server:
  port: 8080

owinfo:
  upload:
    enabled: true
    #FTP?FASTDFS?MINIO
    type: MINIO
    # 预览nginxUrl + remoteDir + "/" + fileRemoteName
    nginxUrl: http://192.168.20.20:80
  ftp:
    host: 192.168.20.20
    port: 21
    username: ftpuser
    password: ftpuser
    # 服务端需要关闭http token验证机制
  fastdfs:
    trackerServers: 192.168.20.20:22122
  minio:
    endpoint: http://192.168.20.20:9000
    username: minioadmin
    password: minioadmin
