server:
  port: 8080


owinfo:
  upload:
    enabled: true
    endpointEnabled: true
    #FTP?FASTDFS?MINIO, 还是FTP好用
    type: FTP
    # 预览nginxUrl + remoteDir + "/" + fileRemoteName
    nginxUrl: http://192.168.20.20:80
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://192.168.0.109:1433;DatabaseName=macao_mpw2_dev
    username: macao_mpw2
    password: 1Hg6Xb0AMigHSev
  ftp:
    host: 192.168.20.20
    port: 21
    username: ftpuser
    password: ftpuser
    # 服务端需要关闭http token验证机制
  fastdfs:
    trackerServers: 192.168.20.20:22122
  minio:
    endpoint: http://192.168.20.20:9000
    username: minioadmin
    password: minioadmin

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB



